version: '3.1'

services:
  mysql-db: 
    image: mysql:latest
    restart: always 
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
    ports:
      - 3306:3306
    volumes: 
      - ./docker-data/mysql-db:/var/lib/mysql  
      



