version: '3.1'

services:
  mysql-db: 
    image: mysql:latest
    restart: always 
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
    ports:
      - 3306:3306
    volumes: 
      - mysql-data:/var/lib/mysql  
      
volumes:
  mysql-data:
      



